worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    client_max_body_size 20M;
    
    limit_req_zone $binary_remote_addr zone=ddos_limit:10m rate=50r/s;

    upstream gateway {
        server api-gateway:3000;
    }

    server {
        listen 80;
        server_name localhost;

        # Socket.io cần duy trì kết nối TCP liên tục (không bị timeout)
        location /socket.io/ {
            proxy_pass http://gateway;
            
            # Bắt buộc cho WebSocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            # Truyền thông tin gốc
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Ngăn NGINX tự động ngắt kết nối WebSocket nếu im lặng quá 60s
            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
        }

        location / {
            limit_req zone=ddos_limit burst=150 nodelay;

            proxy_pass http://gateway;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Tăng timeout cho webhook/thanh toán (để tránh rớt kết nối VNPAY/ZaloPay IPN)
            proxy_read_timeout 60s;
            proxy_connect_timeout 60s;
        }
    }
}
