export enum AppRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CINEMA_MANAGER = 'CINEMA_MANAGER',
  ASSISTANT_MANAGER = 'ASSISTANT_MANAGER',
  TICKET_CLERK = 'TICKET_CLERK',
  CONCESSION_STAFF = 'CONCESSION_STAFF',
  USHER = 'USHER',
  PROJECTIONIST = 'PROJECTIONIST',
  CLEANER = 'CLEANER',
  SECURITY = 'SECURITY',
  CUSTOMER = 'CUSTOMER',
}

export * from './admin';
export * from './permission.constants';
